version: '3'
services:
  bot-rasa:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    container_name: rasa-pet
    networks: 
      - all
    ports:
      - 5006:5005
    volumes:
      - ./:/app
    public: true
    command:
      - run
      - --enable-api
      - --cors
      - "*"

  server-bot-rasa:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: rasa-actions
    networks: 
      - all
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/app/actions"
  
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - /bitnami/mongodb
    public: true

   

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
