version: "3"

services:
  rasa-pet:
    image: rasa/rasa:3.0.4-full
    container_name: rasa-pet
    ports:
      - 5005:5005
    networks:
      - production
    volumes:
      - ./:/app
    # Comentar o public caso venha a rodar a aplicação localmente no docker-compose
    #public: true
    command:
      - run 
      - --enable-api
      - --cors
      - "*"

  web-pet:
    build:
      context: ./web
      dockerfile: web.Dockerfile
    image: web-pet
    container_name: web-pet
    ports:
      - 8080:8080
    networks:
      - production
    depends_on:
      - rasa-pet

  ngrok-pet:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - rasa-pet
    environment:
      - DOMAIN=rasa-pet
      - PORT=5005

networks: 
    production:
        driver: bridge